ifneq ($(TARGET_BOARD_PLATFORM),)

WLAN_SELECT := CONFIG_BCMDHD=m CONFIG_BCMDHD_INSMOD_NO_FW_LOAD=y CONFIG_BROADCOM_WIFI_RESERVED_MEM=y
ifeq ($(BOARD_WLAN_DEVICE_REV),bcm4354)
WLAN_SELECT += CONFIG_BCM4354=m
WLAN_CHIPSET := bcm4354
else
WLAN_SELECT += CONFIG_BCM4339=m
WLAN_CHIPSET := bcm4339
endif

ifeq ($(SEMC_CFG_WLAN_DISABLE_5G),true)
WLAN_SELECT += CONFIG_SEMC_WLAN_BAND=WLC_BAND_2G
endif
ifneq ($(SOMC_CFG_WLAN_BCN_TIMEOUT),)
WLAN_SELECT += CONFIG_SOMC_WLAN_BCN_TIMEOUT=$(SOMC_CFG_WLAN_BCN_TIMEOUT)
endif
ifneq ($(SOMC_CFG_WLAN_LISTEN_INTERVAL),)
WLAN_SELECT += CONFIG_SOMC_WLAN_LISTEN_INTERVAL=$(SOMC_CFG_WLAN_LISTEN_INTERVAL)
endif
ifneq ($(SOMC_CFG_WLAN_NVRAM_PATH),)
WLAN_SELECT += CONFIG_SOMC_WLAN_NVRAM_PATH=$(SOMC_CFG_WLAN_NVRAM_PATH)
endif
ifneq ($(SOMC_CFG_WLAN_KEEP_ALIVE_SETTING),)
WLAN_SELECT += CONFIG_SOMC_WLAN_KEEP_ALIVE_SETTING=$(SOMC_CFG_WLAN_KEEP_ALIVE_SETTING)
endif
ifneq ($(SOMC_CFG_WLAN_SCAN_NPROBES),)
WLAN_SELECT += CONFIG_SOMC_WLAN_SCAN_NPROBES=$(SOMC_CFG_WLAN_SCAN_NPROBES)
endif
WLAN_BLD_DIR := vendor/broadcom/wlan

ifeq ($(SOMC_CFG_WLAN_R1_CHINA_LTA), true)
WLAN_SELECT += CONFIG_SOMC_WLAN_R1_CHINA_LTA=y
endif

LOCAL_PATH := $(call my-dir)

DLKM_DIR := $(TOP)/device/qcom/common/dlkm

###########################################################
KBUILD_OPTIONS := WLAN_ROOT=../$(WLAN_BLD_DIR)
KBUILD_OPTIONS += MODNAME=wlan
KBUILD_OPTIONS += BOARD_PLATFORM=$(TARGET_BOARD_PLATFORM)
KBUILD_OPTIONS += $(WLAN_SELECT)

include $(CLEAR_VARS)
LOCAL_MODULE              := $(BOARD_WLAN_DEVICE).ko
LOCAL_MODULE_KBUILD_NAME  := wlan.ko
LOCAL_MODULE_TAGS         := optional
LOCAL_MODULE_PATH         := $(TARGET_OUT)/lib/modules
include $(DLKM_DIR)/AndroidKernelModule.mk
###########################################################
endif
